language: android
android: 
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23

jdk:
  - openjdk7

sudo: false

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew check --debug

notifications:
  email:
    - roberto.tyley@gmail.com
